### ISSUE TITLE
Linking libraries during build

### ISSUE THREAD

**Issue by miguelaferreira** [cupertino/ectools#1]
I compiled ectools on a Ubuntu box today and had to make some changes to Makefile.

The linker could not find the pthread and ncurses libraries when I ran "make build".
To fix that I moved one "-lncurses" and two "-lpthread" g++ arguments to the end of the respective lines in Makefile.
After that make managed to build ectools without a problem.

**Comment by cupertino** [comment]
Thanks for the advice! I'm developing it on a redhat based distribution so sometimes there is those small changes.
