### ISSUE TITLE
Importing sources in Eclipse

### ISSUE THREAD

**Issue by miguelaferreira** [cupertino/ectools#3]
When importing the sources in Eclipse for C/C++ (Kepler) on Ubuntu (3.8.0-19-generic) I get into several errors.

After I run "Build Project" the error console lists errors in testsuite/old_demos/libec/ex2/MySensor.cpp. When I open that file Eclipse decorates most of the code with errors.
If I exclude the testsuite code then I start to get other errors.

I'm guessing that I'm missing some project specific configuration in Eclipse.
I'm attaching two files:
(1) console-output.png with the output of the build command
(2) problems-list.png with the list of errors I see in the error console

![console-output](https://f.cloud.github.com/assets/4670993/803520/238fe5aa-edf4-11e2-8908-1f0896fc9153.png)

![plroblems-list](https://f.cloud.github.com/assets/4670993/803522/323495e2-edf4-11e2-9b89-e95299f79138.png)

**Comment by cupertino** [comment]
To compile ectools on Eclipse, please follow these steps:
1)  File -> New -> Makefile Project with Existing Code
2)  Project name: ectools
3)  Existing Code Location: $ECTOOLS_ROOT
4)  Toolchain for Indexer Settings: Linux GCC

These should be enougth for the proper compilation of the code. Please let me know if it worked at your platform.

Cheers

**Comment by miguelaferreira** [comment]
I've followed the 4 steps exactly and then did Project -> Build Project.
The Problems tab shows now errors related to pthread. See attached images.

![screen shot 2013-07-16 at 14 54 02](https://f.cloud.github.com/assets/4670993/804708/e106d1a8-ee16-11e2-961c-81cbba470a54.png)
![screen shot 2013-07-16 at 14 54 25](https://f.cloud.github.com/assets/4670993/804709/e132878a-ee16-11e2-927a-f652c2e06141.png)

**Comment by cupertino** [comment]
Did you remember to change the compilation flags from the Makefile to run on Ubuntu https://github.com/cupertino/ectools/issues/1?

It seems you put it before the source files, try putting it at the end after the -lec flag.

**Comment by cupertino** [comment]
Strange .. can you compile it within your terminal?

**Comment by miguelaferreira** [comment]
Sorry, but I was too hasty in saying that it didn't work both ways. In fact I've checked out the wrong branch. With the Makefile modifications for Ubuntu it builds the project with just warnings.

So, now I have a error free project. :)

Can you please explain to me how to run the unit tests?

**Comment by cupertino** [comment]
Good to know that it worked!

Some data may be accessed by other means but as the time access of each sensor influences it final value, the test only instantiate the sensors and explorer some of its features. They can be found in the bin/test folder but their output are not standard, it may vary according to the test.
