### ISSUE TITLE
Example how to create new sensors

### ISSUE THREAD

**Issue by miguelaferreira** [cupertino/ectools#4]
Hi Leandro,

In a post on a different issue, you said 

> On the ectools documentation you will find an example how to create your own sensors. Please let me know if you face any difficulties.

However, I can't seem to find that example.

Can you please point me to it?

Cheers,
Miguel

**Comment by cupertino** [comment]
Hello Miguel,

  It seems I've forgoten to compile the documentation. I just put it into the git repository. You can also compile your version  with doxygen using the doxyfiles in the doc folder.

  You will find the documentation in 'ectools/doc/html/libec/index.html'.

  Cheers,

Leandro

**Comment by miguelaferreira** [comment]
(sorry for closing this prematurely!)

I did compile the documentation myself, but I still couldn't find the example.
Is it the FakeSensor class?

**Comment by cupertino** [comment]
You can use this FakeSensor to see how it works, but on the 'ectools/doc/html/libec/classcea_1_1PIDSensor.html' file you will two simple examples.

For the poweremeter problem you will need to inherit from the Sensor class instead of PIDSensor.

**Comment by miguelaferreira** [comment]
Ok. Thanks

**Comment by miguelaferreira** [comment]
After browsing the code I saw that the class PloggPowerMeter extend the class PowerMeter.
Since I'm trying to implement a power meter, shouldn't I extend that one too?

**Comment by cupertino** [comment]
Yes you're right! Actually, the PowerMeter class extends from the Sensor class, but its better to use the former.
