### ISSUE TITLE
Wiring WattsUp? Pro meter implementation

### ISSUE THREAD

**Issue by miguelaferreira** [cupertino/ectools#6]
Hi Leandro,

I'm finished with the implementation of the WattsUp? Pro meter sensor and now need to wire it up to the tools.

Shall I do that myself? Or just create a pull request and then you'll do it?

Cheers

**Comment by cupertino** [comment]
Nice! A pull request should be better, then I can double check.
Unfortunately we have no access to this wattmeter..

**Comment by miguelaferreira** [comment]
Ok. I will do the pull request,
Once you've wired it up I can run some tests for you with the meter.

**Comment by miguelaferreira** [comment]
Pull request done.
